services:
  api:
    build:
      context: .
    container_name: ais-backend
    restart: unless-stopped
    ports:
      - "6000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
        npx prisma migrate deploy &&
        node dist/app.js
      "
    networks:
      - ais-network

  db:
    image: postgres:15
    container_name: ais-postgres
    restart: unless-stopped
    env_file: .env

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ais-network

volumes:
  pgdata:

networks:
  ais-network:
# use it like this:
# docker compose -f docker-compose.yml --env-file .env.production up
# y
# docker compose -f docker-compose.yml --env-file .env.development up
